
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADMIRATION CADENA DOT EQUALS FN FOR ID INT LBRACE LEQ LPAREN NUM PLUS PRINTLN RBRACE RPAREN SEMICOLON STRINGhola_loop : FN ID LPAREN RPAREN LBRACE PRINTLN ADMIRATION LPAREN  STRING RPAREN SEMICOLON RBRACE'
    
_lr_action_items = {'FN':([0,],[2,]),'$end':([1,13,],[0,-1,]),'ID':([2,],[3,]),'LPAREN':([3,8,],[4,9,]),'RPAREN':([4,10,],[5,11,]),'LBRACE':([5,],[6,]),'PRINTLN':([6,],[7,]),'ADMIRATION':([7,],[8,]),'STRING':([9,],[10,]),'SEMICOLON':([11,],[12,]),'RBRACE':([12,],[13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'hola_loop':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> hola_loop","S'",1,None,None,None),
  ('hola_loop -> FN ID LPAREN RPAREN LBRACE PRINTLN ADMIRATION LPAREN STRING RPAREN SEMICOLON RBRACE','hola_loop',12,'p_hola_loop','Sintactico.py',78),
]
